[package]
name = "bf_jit"
version = "0.1.0"
authors = ["Seiichi KONDO <seikichi@kmc.gr.jp>"]
edition = "2018"

[dependencies]
cranelift = "0.42.0"
cranelift-module = "0.42.0"
cranelift-simplejit = "0.42.0"
peg = "0.5"

[build-dependencies]
peg = "0.5"
